# Generated by Django 5.0.3 on 2024-05-22 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('effect', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('damage_class', models.CharField(choices=[('physical', 'physical'), ('special', 'special'), ('status', 'status')], max_length=8)),
                ('power', models.PositiveSmallIntegerField(null=True)),
                ('pp', models.PositiveSmallIntegerField()),
                ('accuracy', models.PositiveSmallIntegerField(null=True)),
                ('priority', models.SmallIntegerField(null=True)),
                ('aliment', models.CharField(max_length=255, null=True)),
                ('effect_chance', models.PositiveSmallIntegerField(null=True)),
                ('effect_entries', models.CharField(max_length=2600, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('weight', models.PositiveSmallIntegerField()),
                ('height', models.PositiveSmallIntegerField()),
                ('hp', models.PositiveSmallIntegerField()),
                ('atk', models.PositiveSmallIntegerField()),
                ('def_stat', models.PositiveSmallIntegerField()),
                ('satk', models.PositiveSmallIntegerField()),
                ('sdef', models.PositiveSmallIntegerField()),
                ('spe', models.PositiveSmallIntegerField()),
                ('total_stat', models.PositiveSmallIntegerField()),
                ('sprite', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pok_mov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.move')),
                ('id_pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='Pok_abi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.ability')),
                ('id_pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='Evolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=255)),
                ('details', models.CharField(max_length=511)),
                ('id_evo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_evo', to='website.pokemon')),
                ('id_preevo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_preevo', to='website.pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('double_damage_from', 'double_damage_from'), ('double_damage_to', 'double_damage_to'), ('half_damage_from', 'half_damage_from'), ('half_damage_to', 'half_damage_to'), ('no_damage_from', 'no_damage_from'), ('no_damage_to', 'no_damage_to')], max_length=18)),
                ('id_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_attacker', to='website.tipe')),
                ('id_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_defensor', to='website.tipe')),
            ],
        ),
        migrations.CreateModel(
            name='Pok_typ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.pokemon')),
                ('id_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.tipe')),
            ],
        ),
        migrations.AddField(
            model_name='move',
            name='id_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.tipe'),
        ),
    ]
